### ISSUE TITLE
Chopmas pitsaga izoh

### ISSUE THREAD

**Issue by abdulatifkhan** [atojiyev/chopmas-pitsa#1]
Mahsulotlar ro'yxatini ul'da joylasak yaxshi bo'lardi 😊

**Comment by akbarjondev** [comment]
You are right, I'll try next time

**Comment by atojiyev** [comment]
done!

**Comment by akbarjondev** [comment]
> Mahsulotlar ro'yxatini ul'da joylasak yaxshi bo'lardi blush

done!
